trigger:
  batch: true
  paths:
    include:
    - '*'
    exclude:
    - 'azure-pipelines-maui-master.yml'
    - 'YoutubeMp3Downloader.MAUI/*'
  branches:
    include:
      - 'main'

name: $(Date:yyyy-MM-dd)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

variables:
  #secrets
  - group: WPF-PRO
    console-project: 'YoutubeMp3Downloader.Console\YoutubeMp3Downloader.WPF.csproj'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
        command: restore
        projects: |
         **/*WPF.csproj
         **/*Services.csproj

  # Update appsettings.json via FileTransform task.
  - task: FileTransform@1
    displayName: 'File transformation: appsettings.json'
    inputs:
      folderPath: YoutubeMp3Downloader.WPF
      targetFiles: '**/appsettings.json'
      fileType: json

  - task: DotNetCoreCLI@2
    displayName: "Build & Publish"
    inputs:
      command: publish 
      arguments: -r win-x64 -p:PublishSingleFile=True --self-contained false -o $(build.ArtifactStagingDirectory)
      workingDirectory: YoutubeMp3Downloader.WPF
      publishWebProjects: false
    enabled: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish CONSOLE Artifact"
    inputs:
      ArtifactName: WPF