trigger:
  batch: true
  paths:
    include:
    - '*'
    exclude:
    - 'azure-pipelines-maui-master.yml'
    - 'YoutubeMp3Downloader.MAUI/*'
  branches:
    include:
      - 'main'

name: $(Date:yyyy-MM-dd)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

variables:
  - group: WPF-PROD

steps:
  # Update appsettings.json via FileTransform task.
  - task: AzureAppConfiguration.azure-app-configuration-task.custom-build-release-task.AzureAppConfiguration@5
    displayName: 'Azure App Configuration'
    inputs:
      azureSubscription: $(AzureSubscription)
      AppConfigurationEndpoint: $(AppConfigurationEndpoint)

  - task: FileTransform@1
    displayName: 'File transformation: App.config'
    inputs:
      folderPath: YoutubeMp3Downloader.WPF
      targetFiles: '**/App.config'
      fileType: xml

  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
        command: restore
        projects: |
         **/*WPF.csproj
         **/*Services.csproj

  #- task: DotNetCoreCLI@2
  #  displayName: "Build & Publish"
  #  inputs:
  #    command: publish 
  #    arguments: -r win-x64 -p:PublishSingleFile=True --self-contained false -o $(build.ArtifactStagingDirectory)
  #    workingDirectory: YoutubeMp3Downloader.WPF
  #    publishWebProjects: false
  #  enabled: true

# https://github.com/it3xl/MSBuild-DevEnv-Build-Server-Workarounds/issues/1#issuecomment-525435637
  - task: BatchScript@1
    displayName: Enable .vdproj Builds
    inputs:
      filename: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild\DisableOutOfProcBuild.exe"'
      workingFolder: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild"'

  - script: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com" $(System.DefaultWorkingDirectory)\YoutubeMp3Downloader.sln /Build "Release" /Project $(System.DefaultWorkingDirectory)\YoutubeMp3Downloader.WPF.Setup\YoutubeMp3Downloader.WPF.Setup.vdproj'
    displayName: Build Installer

  - task: PublishBuildArtifacts@1
    displayName: "Publish Installer"
    inputs:
      pathToPublish: $(System.DefaultWorkingDirectory)\YoutubeMp3Downloader.WPF.Setup\Release\YoutubeMp3Downloader.WPF.Setup.msi
      ArtifactName: YoutubeMp3Downloader Installer
      
  #- task: AppCenterDistribute@3
  #  displayName: 'Deploy YoutubeMp3Downloader to Visual Studio App Center'
  #  inputs:
  #      serverEndpoint: 'YoutubeMp3DownloaderApp'
  #      appSlug: $(AppSlug)
  #      appFile: $(System.DefaultWorkingDirectory)\YoutubeMp3Downloader.WPF.Setup\Release\YoutubeMp3Downloader.WPF.Setup.msi
  #      buildVersion: 1
  #      symbolsIncludeParentDirectory: false
  #      releaseNotesInput: 1
  #      isSilent: false

# Azure file copy
# Copy files to Azure Blob Storage or virtual machines
  - task: AzureFileCopy@4
    inputs:
      sourcePath:  $(System.DefaultWorkingDirectory)\YoutubeMp3Downloader.WPF.Setup\Release\YoutubeMp3Downloader.WPF.Setup.msi
      azureSubscription:  $(AzureSubscription)
      destination: azureBlob
      storage: $(StorageAccountName)
      containerName: $(ContainerName)
      #blobPrefix: # Optional
      #resourceGroup: # Required when destination == AzureVMs
      #resourceFilteringMethod: 'machineNames' # Optional. Options: machineNames, tags
      #machineNames: # Optional
      #vmsAdminUserName: # Required when destination == AzureVMs
      #vmsAdminPassword: # Required when destination == AzureVMs
      #targetPath: # Required when destination == AzureVMs
      #additionalArgumentsForBlobCopy: # Optional
      #additionalArgumentsForVMCopy: # Optional
      #enableCopyPrerequisites: false # Optional
      #copyFilesInParallel: true # Optional
      #cleanTargetBeforeCopy: false # Optional
      #skipCACheck: true # Optional
      #sasTokenTimeOutInMinutes: # Optional
      name: AzureFileCopy
  - script: | 
      echo $(AzureFileCopy.StorageContainerUri)
      echo $(AzureFileCopy.StorageContainerSasToken)
