trigger:
  batch: true
  paths:
    include:
    - '*'
    exclude:
    - 'azure-pipelines-maui-master.yml'
    - 'YoutubeMp3Downloader.MAUI/*'
  branches:
    include:
      - 'main'

name: $(Date:yyyy-MM-dd)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

variables:
  - group: WPF-PROD

steps:
  # Update appsettings.json via FileTransform task.
  - task: AzureAppConfiguration.azure-app-configuration-task.custom-build-release-task.AzureAppConfiguration@5
    displayName: 'Azure App Configuration'
    inputs:
      azureSubscription: $(AzureSubscription)
      AppConfigurationEndpoint: $(AppConfigurationEndpoint)

  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
        command: restore
        projects: |
         **/*WPF.csproj
         **/*Services.csproj

  - task: DotNetCoreCLI@2
    displayName: "Build & Publish"
    inputs:
      command: publish 
      arguments: -r win-x64 -p:PublishSingleFile=True --self-contained false -o $(build.ArtifactStagingDirectory)
      workingDirectory: YoutubeMp3Downloader.WPF
      publishWebProjects: false
    enabled: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish WPF Artifact"
    inputs:
      ArtifactName: WPF

      
  - task: AppCenterDistribute@3
    displayName: 'Deploy YoutubeMp3Downloader to Visual Studio App Center'
    inputs:
        serverEndpoint: 'YoutubeMp3DownloaderApp'
        appSlug: $(AppSlug)
        appFile: $(build.ArtifactStagingDirectory)
        buildVersion: 1
        symbolsIncludeParentDirectory: false
        releaseNotesInput: 1
        isSilent: false