trigger:
- master

pool:
  vmImage: 'windows-2022'

variables:
  - group: YoutubeMp3DownloaderUwpProd
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'x86|x64|ARM64'
  - name: buildConfiguration
    value: 'Release'
  - name: appxPackageDir
    value: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:

## This is required because the windows-2022 image dropped
## support for this Store Engagement SDK, and YoutubeMp3Downloader uses it.
- task: PowerShell@2
  displayName: 'Installing Microsoft Store Engagement SDK'
  inputs:
    targetType: 'inline'
    script: |
      $sdkUrl = '$(EngagementSdkMsiUrl)'
      $msiPath = Join-Path $env:TEMP "Setup.msi"
      Write-Output "downloading $sdkUrl"
      Invoke-WebRequest -Uri $sdkUrl -OutFile $msiPath
      Write-Output "Installing $msiPath"
      Start-Process $msiPath -ArgumentList "/q" -Wait
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [xml]$xmlDoc = Get-Content $(Build.SourcesDirectory)\src\YoutubeMp3Downloader.Uwp\Package.appxmanifest
      $xmlDoc.Package.Identity.Name="JGCarmona.YoutubeMp3Downloader"
      $xmlDoc.Package.Properties.DisplayName="Youtube Mp3 Downloader"
      $xmlDoc.Package.Applications.Application.VisualElements.DisplayName="Youtube Mp3 Downloader"
      $xmlDoc.Save('$(Build.SourcesDirectory)\YoutubeMp3Downloader.Uwp\Package.appxmanifest')
    failOnStderr: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [xml]$xmlDoc = Get-Content $(Build.SourcesDirectory)\src\AmbientSounds.Uwp\appsettings.resw
      $xmlDoc.SelectSingleNode("//root/data[@name='AppVersion']").Value = "$(AppVersion)"
      $xmlDoc.SelectSingleNode("//root/data[@name='AppCenterSecret']").Value = "$(AppCenterSecret)"
      $xmlDoc.Save('$(Build.SourcesDirectory)\src\YoutubeMp3Downloader.Uwp\appsettings.resw')
    failOnStderr: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    platform: 'x64'
    solution: '**/AmbientSounds.Uwp.csproj'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=CI'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'